title: Notes
author: sigtrap1024
email: sigtrap1024 at Google's email service
description: > # this means to ignore newlines until "baseurl:"
  Programming, math, systems.
  
# social links
github_username:  sigtrap1024 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
